name: community
description: NA
mailing_list: hccl@open-ascend.org
meeting_url: NA
mentors: []
committers:
- gitcode_id: mywaaagh_admin
  name: 李超然
  email: lichaoran1@huawei.com
- gitcode_id: drizzlezyk
  name: 钟源珂
  email: zhongyuanke@huawei.com
reviewers:
- gitcode_id: mywaaagh_admin
  name: 李超然
  email: lichaoran1@huawei.com
- gitcode_id: drizzlezyk
  name: 钟源珂
  email: zhongyuanke@huawei.com
repositories:
- repo:
  - Ascend/community
  - Ascend/infrastructure
