name: infrastructure
description: NA
tc_members:
  - gitcode_id: mywaaagh_admin
    name: 李超然
    email: lichaoran1@huawei.com
  - gitcode_id: drizzlezyk
    name: 钟源珂
    email: zhongyuanke@huawei.com

sigs:
  - sig_name: community
    maintainers:
      - gitcode_id: mywaaagh_admin
        name: 李超然
        email: lichaoran1@huawei.com
      - gitcode_id: drizzlezyk
        name: 钟源珂
        email: zhongyuanke@huawei.com
