name: infrastructure
description: NA
mailing_list: NA
meeting_url: NA
mentors: []
committers:
- gitcode_id: drizzlezyk
  name: 钟源珂
  email: zhongyuanke@huawei.com
- gitcode_id: TommyLike
  name: 胡胜
  email: hu.husheng@huawei.com
- gitcode_id: ZhengZhenyu
  name: 郑振宇
  email: zhengzhenyu@huawei.com
- gitcode_id: zeshengzong
  name: 宗泽升
  email: zongzesheng@huawei.com
- gitcode_id: gcw_u8HHrTWX
  name: 谢文静
  email: xiewenjing4@huawei.com
- gitcode_id: tianll111
  name: 田力
  email:  tianli19@huawei.com
- gitcode_id: james88liu
  name: 刘建星
  email:  liujianxing1@huawei.com
- gitcode_id: aflyingto
  name: 吴鹏飞
  email: wupengfei10@huawei.com
- gitcode_id: dd4574bb
  name: 丁健坤
  email: dingjiankun@huawei.com
- gitcode_id: zxf_0731
  name: 赵栩锋
  email: zhaoxufeng5@huawei.com
- gitcode_id: dilililiwhy
  name: 吴环宇
  email: why.wuhuanyu@huawei.com
- gitcode_id: wujinyuan1
  name: 吴金源
  email: wujinyuan1@huawei.com
- gitcode_id: overfitting_zh
  name: 张涵
  email: zhanghan72@huawei.com
- gitcode_id: frankang
  name: 康富安
  email: kangfuan2@huawei.com
reviewers:
- gitcode_id: Coopermassaki
  name: 付勇
  email: fuyong29@h-partners.com
- gitcode_id: jy834507063
  name: 金逸
  email: jinyi20@h-partners.com
- gitcode_id: ZeesangPie
  name: 程郎
  email: chenglang11@huawei.com
repositories:
  - repo:
    - Ascend/community
    - Ascend/infrastructure
    - Ascend/.gitcode
    - Ascend/ci-infra
  - repo:
    - Ascend/agent-skills
    committers:
      - gitcode_id: fyfugoyfa
        name: 曾浩龙
        email: zenghaolong@huawei.com
      - gitcode_id: agent0
        name: 占杰
        email: zhanjie4@huawei.com
      - gitcode_id: hejianping
        name: 何建平
        email: hejianping7@huawei.com

