name: infrastructure
description: NA
mailing_list: NA
meeting_url: NA
mentors: []
committers:
- gitcode_id: mywaaagh_admin
  name: 李超然
  email: lichaoran1@huawei.com
- gitcode_id: drizzlezyk
  name: 钟源珂
  email: zhongyuanke@huawei.com
- gitcode_id: TommyLike
  name: 胡胜
  email: hu.husheng@huawei.com
- gitcode_id: zhengzhenyu
  name: 郑振宇
  email: zhengzhenyu@huawei.com
- gitcode_id: zeshengzong
  name: 宗泽升
  email: zongzesheng@huawei.com
reviewers:
- gitcode_id: Coopermassaki
  name: 付勇
  email: fuyong29@h-partners.com
repositories:
- repo:
  - Ascend/community
  - Ascend/infrastructure
